In [2]:
import numpy as np

In [3]:
y = np.arange(3)

In [1]:
y

NameError: name 'y' is not defined

In [5]:
np.shape(y)

(3,)

In [6]:
y.reshape(-1,1)

array([[0],
       [1],
       [2]])

In [7]:
y.reshape(1,-1)

array([[0, 1, 2]])

In [8]:
y[None,:]

array([[0, 1, 2]])

In [9]:
np.shape(y.reshape(-1,1))

(3, 1)

In [10]:
a = []
a.append(None)
w1 = np.random.rand(1,2)
a.append(w1)

In [11]:
a

[None, array([[0.68437598, 0.53411868]])]

In [12]:
w2 = np.random.rand(2,3)
a.append(w2)

In [13]:
a

[None,
 array([[0.68437598, 0.53411868]]),
 array([[0.1248112 , 0.7194419 , 0.28751663],
        [0.53988025, 0.15358034, 0.0536998 ]])]

In [14]:
a[1]

array([[0.68437598, 0.53411868]])

In [15]:
a = np.array(a)

In [16]:
a

array([None, array([[0.68437598, 0.53411868]]),
       array([[0.1248112 , 0.7194419 , 0.28751663],
       [0.53988025, 0.15358034, 0.0536998 ]])], dtype=object)

In [17]:
type(a)

numpy.ndarray

In [18]:
a[0] = np.random.rand(2,3)
a

array([array([[0.42761331, 0.16459935, 0.29535054],
       [0.82053099, 0.11883579, 0.98160443]]),
       array([[0.68437598, 0.53411868]]),
       array([[0.1248112 , 0.7194419 , 0.28751663],
       [0.53988025, 0.15358034, 0.0536998 ]])], dtype=object)

In [19]:
a[0]

array([[0.42761331, 0.16459935, 0.29535054],
       [0.82053099, 0.11883579, 0.98160443]])

In [24]:
np.random.rand()

0.15625506045499227

In [25]:
a = np.array([1,2,3])

In [26]:
a + 1

array([2, 3, 4])

In [28]:
a.reshape(-1,1) + 3

array([[4],
       [5],
       [6]])

<module 'numpy' from 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [5]:
y = np.arange(4)

In [9]:
y = y.reshape(1,-1)
np.shape(y)

(1, 4)

In [12]:
np.diagflat(y)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])